"""Compute NUPACK ensemble defect vs WT structure (Dirks et al. 2004) + WT
structure Boltzmann probability (Ward et al. 2023).

Ensemble defect measures how far each mutant's Boltzmann ensemble deviates from
the WT MFE structure (a computational target, not a validated binding fold).
For each position i:
  - if i pairs with j in the WT target, term = p_ij(mutant)
  - if i is unpaired in WT target, term = P[i,i](mutant)
  defect = n - sum of those terms (0 = folds exactly like WT).

wt_struct_prob = P(mutant folds into the WT dot-bracket) — Ward et al. (NAR
2023, gkad097) found target-structure probability more discriminative than
ensemble defect on natural sequences.

IMPORTANT environment note: run with the server's `nupack_env_py39` Python
(Python 3.9 + nupack 4.0.0.27). The Python 3.10 `nupack_env` segfaults in
mfe/pairs/pfunc on 141nt strands (diagnosed 2026-09-24, tools/nupack_diag.py).

Output: runs/new_features/ensemble_defect.csv (Sequence, ensemble_defect,
wt_struct_prob, per-site defect at the 13 mutation positions).

2026-10-06: unpaired correctness now uses the NUPACK pairs diagonal. Saved
features generated by the prior row-sum implementation must be recomputed.
Historical ``defect_pos`` columns contain correctness probabilities, not
per-position defects. Invalid target pairs are now identified explicitly;
unexpected calculation failures are persisted and abort a formal run.
"""

from __future__ import annotations

import argparse
import multiprocessing as mp
import time
import json
from pathlib import Path

import numpy as np
import pandas as pd

import nupack

try:
    from .structure_metrics import target_structure_metrics
except ImportError:
    from structure_metrics import target_structure_metrics

PROJECT_ROOT = Path(__file__).resolve().parents[2]

BASES = "ACGU"
MUT_POS = [30, 31, 32, 33, 89, 90, 91, 92, 127, 128, 129, 130, 131]
WT_141 = ("UAUCCUUCGGGGCAGGGUGGAAAUCCCGACCGGCGGUAGUAAAGCACAUUUGCUUUAGAGCCC"
          "GUGACCCGUGUGCAUAAGCACGCGGUGGAUUCAGUUUAAGCUGAAGCCGACAGUGAAAGUCUGGA"
          "UGGGAGAAGGAUG")

_MODEL = None
_TARGET_PARTNER = None  # list: partner index (0-based) or -1 if unpaired
_WT_STRUCT = None       # WT MFE dot-bracket string (for structure_probability)


def _get_model():
    global _MODEL
    if _MODEL is None:
        nupack.config.threads = 1
        _MODEL = nupack.Model(material="rna", celsius=30)
    return _MODEL


def _to_dotparen(structure):
    """Normalize a nupack Structure to a dot-paren string.

    nupack 4.0 `mfe(...).structure` is a `nupack.core.Structure` whose str()
    is the dot-paren string (do NOT iterate it — iteration yields pair-index
    internals, which previously produced bogus non-canonical pairs).
    """
    if isinstance(structure, str):
        return structure
    s = str(structure)
    if s and all(c in ".()" for c in s):
        return s
    raise ValueError(f"unexpected structure representation: {type(structure)}")


def _target_from_dotbracket(struct):
    """Return partner[0-based] per position, -1 if unpaired."""
    n = len(struct)
    partner = [-1] * n
    stack = []
    for i, c in enumerate(struct):
        if c == "(":
            stack.append(i)
        elif c == ")":
            if not stack:
                raise ValueError(f"unbalanced dot-bracket at position {i}")
            j = stack.pop()
            partner[i] = j
            partner[j] = i
    if stack:
        raise ValueError("unbalanced dot-bracket: unclosed '('")
    return partner


def compute_wt_target():
    s = nupack.Strand(WT_141, name="wt")
    c = nupack.Complex([s])
    mfe = nupack.mfe(c, model=_get_model())
    struct = _to_dotparen(mfe[0].structure)
    return struct, _target_from_dotbracket(struct)


def compute_defect(seq):
    """Return (global_defect, per_site_defect[13], wt_structure_probability).

    wt_structure_probability = P(sequence folds into the WT MFE structure),
    the Boltzmann weight of the WT dot-bracket under this mutant's ensemble
    (Ward et al. 2023: target-structure probability is more discriminative
    than ensemble defect for natural sequences).
    """
    s = nupack.Strand(seq, name="s")
    c = nupack.Complex([s])
    pp = nupack.pairs(c, model=_get_model()).to_array()  # (n, n)
    defect, per_site = target_structure_metrics(pp, _TARGET_PARTNER, MUT_POS)
    allowed = {'AU', 'UA', 'GC', 'CG', 'GU', 'UG'}
    invalid = any(seq[i]+seq[j] not in allowed for i,j in enumerate(_TARGET_PARTNER) if j>i)
    if invalid:
        wt_prob = 0.0
    else:
        wt_prob = float(nupack.structure_probability(strands=[s], structure=_WT_STRUCT, model=_get_model()))
    return defect, per_site, wt_prob, 'invalid_target_pair' if invalid else 'computed'


def _worker(seq):
    try:
        return compute_defect(seq)
    except Exception as e:
        return {'error_type':type(e).__name__, 'error':str(e), 'Sequence':seq}


def _init_worker(target_partner, wt_struct):
    """Pool initializer: copies the WT target into each worker process.

    Required for Windows `spawn` (and safe on `fork`): module globals are NOT
    inherited by spawned children, so passing `_TARGET_PARTNER` via initargs is
    the only way workers see it. Without this, every worker returned None/NaN.
    """
    global _TARGET_PARTNER, _WT_STRUCT
    _TARGET_PARTNER = target_partner
    _WT_STRUCT = wt_struct


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default="data/proxy2000_v2")
    ap.add_argument("--n-jobs", type=int, default=8)
    ap.add_argument("--output", default="runs/new_features/ensemble_defect.csv")
    args = ap.parse_args()

    data_dir = PROJECT_ROOT / args.data_dir
    df = pd.read_csv(data_dir / "fad_proxy2000_v2_full.csv")
    seqs = [str(s).upper().replace("T", "U") for s in df["Sequence"]]

    t0 = time.time()
    global _TARGET_PARTNER, _WT_STRUCT
    wt_struct, _TARGET_PARTNER = compute_wt_target()
    _WT_STRUCT = wt_struct
    print(f"WT MFE structure: {wt_struct} ({time.time()-t0:.0f}s)")

    # time one sequence
    t1 = time.time()
    d, _, wp, _ = compute_defect(seqs[0])
    print(f"one sequence defect={d:.2f} wt_prob={wp:.4f} in {time.time()-t1:.1f}s -> "
          f"est total {len(seqs)*(time.time()-t1)/args.n_jobs:.0f}s with {args.n_jobs} jobs")

    results = []
    with mp.Pool(args.n_jobs, initializer=_init_worker,
                 initargs=(_TARGET_PARTNER, _WT_STRUCT)) as pool:
        for i, r in enumerate(pool.imap(_worker, seqs)):
            results.append(r)
            if (i + 1) % 200 == 0:
                print(f"  {i+1}/{len(seqs)}  {time.time()-t0:.0f}s")

    errors = [r for r in results if isinstance(r,dict)]
    out = PROJECT_ROOT / args.output
    out.parent.mkdir(parents=True, exist_ok=True)
    (out.parent/'nupack_errors.json').write_text(json.dumps(errors,indent=2))
    if errors:
        raise RuntimeError(f'{len(errors)} NUPACK errors; see nupack_errors.json; no silent zero substitution')
    valid = results
    print(f"computed {len(valid)}/{len(seqs)} in {time.time()-t0:.0f}s")
    if not valid:
        raise RuntimeError(
            "all ensemble-defect computations failed; check the nupack "
            "environment (nupack 4.0, celsius=30) and the WT MFE structure"
        )

    out_df = pd.DataFrame({
        "Sequence": seqs,
        "ensemble_defect": [r[0] if r else np.nan for r in results],
        "wt_struct_prob": [r[2] if r else np.nan for r in results],
        "probability_status": [r[3] for r in results],
    })
    for k, pos in enumerate(MUT_POS):
        out_df[f"correctness_pos{pos}"] = [r[1][k] for r in results]

    checks=[]
    # NUPACK 4.0.0.27's utility defect uses the design constraint solver and
    # rejects sequence/target pairs with noncanonical target base pairs.
    # Validate every compatible WT target, then both diagonal-only and each
    # sequence's own MFE target on the first 20. The measured feature target
    # remains WT for all 2000; diagnostic alternate targets are never features.
    cases=[(seq,_WT_STRUCT,r[0],'compatible_WT_target') for seq,r in zip(seqs,results) if r[3]=='computed']
    for seq in seqs[:20]:
        pp=nupack.pairs(strands=[seq],model=_get_model()).to_array()
        own=_to_dotparen(nupack.mfe(strands=[seq],model=_get_model())[0].structure)
        for target,kind in [('.'*len(seq),'all_unpaired_diagnostic'),(own,'own_MFE_diagnostic')]:
            ours=target_structure_metrics(pp,_target_from_dotbracket(target),MUT_POS)[0]
            cases.append((seq,target,ours,kind))
    for seq,target,ours,kind in cases:
        official=float(nupack.defect(strands=[seq],structure=target,model=_get_model()))*len(seq)
        delta=abs(official-ours); checks.append({'Sequence':seq,'target':target,'kind':kind,'official_count':official,'ours_count':ours,'absolute_error':delta})
        if delta>1e-5:
            raise RuntimeError(f'official NUPACK defect mismatch: {delta}')
    (out.parent/'nupack_validation.json').write_text(json.dumps({'nupack_version':nupack.__version__,'material':'rna','celsius':30,'target':_WT_STRUCT,'checks':checks,'n_errors':len(errors),'status_counts':out_df.probability_status.value_counts().to_dict(),'official_incompatible_WT_target_checks':'not supported by design-based utility; explicit diagnostic failure retained separately','elapsed_seconds':time.time()-t0},indent=2))

    out = PROJECT_ROOT / args.output
    out.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(out, index=False)
    print(f"[OK] -> {out}")


if __name__ == "__main__":
    main()
